
// New Rule Types
export const UPDATE_PATH    = 'UPDATE_PATH'
export const UPDATE_STATUS  = 'UPDATE_STATUS'
export const UPDATE_METHOD  = 'UPDATE_METHOD'
export const UPDATE_BODY    = 'UPDATE_BODY'
export const CLEAR_NEW_RULE = 'CLEAR_NEW_RULE'

// Rule Types
export const TOGGLE_RULE_DISABLED = 'TOGGLE_RULE_DISABLED'
export const TOGGLE_RULE_SKIP_API = 'TOGGLE_RULE_SKIP_API'
export const TOGGLE_RULE_INT_REQ  = 'TOGGLE_RULE_INT_REQ'
export const TOGGLE_RULE_INT_RES  = 'TOGGLE_RULE_INT_RES'
export const UPDATE_RULE_BODY     = 'UPDATE_RULE_BODY'

// Intercepted
export const ADD_NEW_REQUEST  = 'ADD_NEW_REQUEST'
export const ADD_NEW_RESPONSE = 'ADD_NEW_RESPONSE'
